version: '3'
services:
  # PostgreSQL database
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432 # Adjust the port if needed
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - airways-network

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - database
    ports:
      - 82:80
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - airways-network

  #redis
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

networks:
  airways-network:
    driver: bridge

volumes:
  db-data:
  pgadmin-data:
